name: Run Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup go
#         uses: actions/setup-go@v2
#         with:
#           go-version: '1.18'
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Setup golangci-lint
#         uses: golangci/golangci-lint-action@v3.2.0
#         with:
#           version: v1.45.0
#           args: --verbose
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: get package
        run: go get

      - name: Run Tests
        run: go test ./...

#       - name: Upload coverage to Codecov
#         uses: codecov/codecov-action@v2
